#
#     Copyright (C) 2010-2015 Marvell International Ltd.
#     Copyright (C) 2002-2010 Kinoma, Inc.
#     
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#       http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
 %: force
#		 @$(MAKE) -f make_F.mk clean
#		 @$(MAKE) -f make_F.mk
#		 @$(MAKE) -f make_G.mk clean
#		 @$(MAKE) -f make_G.mk
#		 @$(MAKE) -f make_H.mk clean
#		 @$(MAKE) -f make_H.mk
#		 @$(MAKE) -f make_I.mk clean
#		 @$(MAKE) -f make_I.mk
#		 @$(MAKE) -f make_J.mk clean
#		 @$(MAKE) -f make_J.mk
		 @$(MAKE) -f make_java.mk clean
		 @$(MAKE) -f make_java.mk
 force: ;

