include (CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR "aspen")

SET(TOOL_PREFIX arm-marvell-linux-gnueabi-)
SET(FSK_SYSROOT_LIB $ENV{FSK_SYSROOT_LIB})

FIND_PATH(TOOLCHAIN_BIN ${TOOL_PREFIX}gcc $ENV{PATH} $ENV{ARM_MARVELL_LINUX_GNUEABI}/bin)

SET(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN}/${TOOL_PREFIX}gcc CACHE PATH "assembler")
CMAKE_FORCE_C_COMPILER (${TOOLCHAIN_BIN}/${TOOL_PREFIX}gcc GNU)
CMAKE_FORCE_CXX_COMPILER (${TOOLCHAIN_BIN}/${TOOL_PREFIX}gcc GNU)
SET(CMAKE_ASM_SOURCE_FILE_EXTENSIONS gas7;gas;s)
SET(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> -c -x assembler-with-cpp -o <OBJECT> <SOURCE>")

SET(AS_NEON ${TOOL_PREFIX}as)
SET(AS_NEON_OPTIONS -mfpu=neon)
SET(AS_OPTIONS -c -x assembler-with-cpp)
SET(AS_V7 ${TOOL_PREFIX}as)
SET(AS_V7_OPTIONS )
SET(AS_WMMX ${TOOL_PREFIX}as)
SET(AS_WMMX_OPTIONS -mwmmxt)

SET(FREETYPE_VERSION 2.6)
SET(FREETYPE_DIR ${TMP_DIR}/freetype-${FREETYPE_VERSION})
