#
#     Copyright (C) 2010-2015 Marvell International Ltd.
#     Copyright (C) 2002-2010 Kinoma, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
binary(SOURCE ${MC_DIR}/application.js)
binary(SOURCE ${MC_DIR}/extensions/coap.js)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith.js)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_ec.js MODULE ec SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_ecp.js MODULE ecp SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_ed.js MODULE ed SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_int.js MODULE int SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_mod.js MODULE mod SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_mont.js MODULE mont SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/arith_z.js MODULE z SUBDIR arith)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt.js)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_aead.js MODULE aead SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_aes.js MODULE aes SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_ber.js MODULE ber SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_cbc.js MODULE cbc SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_chacha.js MODULE chacha SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_cipher.js MODULE cipher SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_ctr.js MODULE ctr SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_curve25519.js MODULE curve25519 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_des.js MODULE des SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_digest.js MODULE digest SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_dsa.js MODULE dsa SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_ecb.js MODULE ecb SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_ecdsa.js MODULE ecdsa SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_ed25519.js MODULE ed25519 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_ed25519_c.js MODULE ed25519_c SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_hkdf.js MODULE hkdf SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_hmac.js MODULE hmac SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_md5.js MODULE md5 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_mode.js MODULE mode SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_oaep.js MODULE oaep SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_pkcs1.js MODULE pkcs1 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_pkcs1_5.js MODULE pkcs1_5 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_pkcs8.js MODULE pkcs8 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_poly1305.js MODULE poly1305 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_rc4.js MODULE rc4 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_rng.js MODULE rng SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_rsa.js MODULE rsa SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_sha1.js MODULE sha1 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_sha256.js MODULE sha256 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_sha512.js MODULE sha512 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_srp.js MODULE srp SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_stream.js MODULE stream SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_tdes.js MODULE tdes SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/crypt/crypt_x509.js MODULE x509 SUBDIR crypt)
binary(SOURCE ${MC_DIR}/extensions/dial.js)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/pinexplorer.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/simulator/Analog.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/simulator/Digital.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/simulator/Ground.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/simulator/I2C.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/simulator/Power.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/dial/pinexplorer/simulator/Serial.js SUBDIR dial/pinexplorer)
binary(SOURCE ${MC_DIR}/extensions/ext_bin.js MODULE bin)
binary(SOURCE ${MC_DIR}/extensions/ext_dhcpd.js MODULE dhcpd)
binary(SOURCE ${MC_DIR}/extensions/ext_http.xs MODULE http)
binary(SOURCE ${MC_DIR}/extensions/ext_http_client.xs MODULE HTTPClient)
binary(SOURCE ${MC_DIR}/extensions/ext_http_server.xs MODULE HTTPServer)
binary(SOURCE ${MC_DIR}/extensions/ext_json.xs MODULE json)
binary(SOURCE ${MC_DIR}/extensions/ext_mdns.js MODULE mdns)
binary(SOURCE ${MC_DIR}/extensions/ext_secure_socket.js MODULE SecureSocket)
binary(SOURCE ${MC_DIR}/extensions/ext_ssdp.xs MODULE SSDPMessage)
binary(SOURCE ${MC_DIR}/extensions/ext_ssdp_control.xs MODULE SSDPControl)
binary(SOURCE ${MC_DIR}/extensions/ext_ssdp_device.xs MODULE SSDPDevice)
binary(SOURCE ${MC_DIR}/extensions/ext_uuid.xs MODULE uuid)
binary(SOURCE ${MC_DIR}/extensions/hap/hap.js)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_constants.js MODULE constants SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_hkdf_sha512.js MODULE hkdf_sha512 SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_ie.js MODULE ie SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_mfi.js MODULE mfi SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_pairing.js MODULE pairing SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_setup.js MODULE setup SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_socket.js MODULE socket SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_tlv.js MODULE tlv SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/hap_verify.js MODULE verify SUBDIR hap)
binary(SOURCE ${MC_DIR}/extensions/hap/wac.js)
binary(SOURCE ${MC_DIR}/extensions/inetd_studio.js MODULE StudioHTTPServer)
binary(SOURCE ${MC_DIR}/extensions/inetd_telnetd.js MODULE telnetd)
binary(SOURCE ${MC_DIR}/extensions/inetd_tftpd.js MODULE tftpd)
binary(SOURCE ${MC_DIR}/extensions/io/io_a2d.js MODULE A2D SUBDIR io)
binary(SOURCE ${MC_DIR}/extensions/io/io_i2c.js MODULE I2C SUBDIR io)
binary(SOURCE ${MC_DIR}/extensions/io/io_uart.js MODULE Serial SUBDIR io)
binary(SOURCE ${MC_DIR}/extensions/kunit.js)
binary(SOURCE ${MC_DIR}/extensions/logging.js)
binary(SOURCE ${MC_DIR}/extensions/mqtt.js)
binary(SOURCE ${MC_DIR}/extensions/net.js)
binary(SOURCE ${MC_DIR}/extensions/pinmux.js)
binary(SOURCE ${MC_DIR}/extensions/pins/bll_Analog.js MODULE Analog)
binary(SOURCE ${MC_DIR}/extensions/pins/bll_Digital.js MODULE Digital)
binary(SOURCE ${MC_DIR}/extensions/pins/bll_Ground.js MODULE Ground)
binary(SOURCE ${MC_DIR}/extensions/pins/bll_I2C.js MODULE I2C)
binary(SOURCE ${MC_DIR}/extensions/pins/bll_Power.js MODULE Power)
binary(SOURCE ${MC_DIR}/extensions/pins/bll_Serial.js MODULE Serial)
binary(SOURCE ${MC_DIR}/extensions/pins/pins.js)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_Analog.js MODULE Analog SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_Digital.js MODULE Digital SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_GPIO.js MODULE GPIO SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_Ground.js MODULE Ground SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_I2C.js MODULE I2C SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_K5PinMux.js MODULE K5PinMux SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_Power.js MODULE Power SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_PowerGround.js MODULE PowerGround SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_Serial.js MODULE Serial SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins__hap.js MODULE _hap SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins__http.js MODULE _http SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/pins/pins_map.js MODULE map SUBDIR pins)
binary(SOURCE ${MC_DIR}/extensions/setup/config.js SUBDIR setup)
binary(SOURCE ${MC_DIR}/extensions/setup/connect.js SUBDIR setup)
binary(SOURCE ${MC_DIR}/extensions/setup/description.js SUBDIR setup)
binary(SOURCE ${MC_DIR}/extensions/setup/download.js SUBDIR setup)
binary(SOURCE ${MC_DIR}/extensions/setup/rssi.js SUBDIR setup)
binary(SOURCE ${MC_DIR}/extensions/setup/scan.js SUBDIR setup)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl.js)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_alert.js MODULE alert SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_cache.js MODULE cache SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_cert_mc.js MODULE cert_mc SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_changecipher.js MODULE changecipher SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_ciphersuites.js MODULE ciphersuites SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_handshake.js MODULE handshake SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_prf.js MODULE prf SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_protocol.js MODULE protocol SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_record.js MODULE record SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_session.js MODULE session SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_setup.js MODULE setup SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/ssl/ssl_stream.js MODULE stream SUBDIR ssl)
binary(SOURCE ${MC_DIR}/extensions/utils.js)
binary(SOURCE ${MC_DIR}/extensions/websocket.js)
binary(SOURCE ${MC_DIR}/inetd.js)
binary(SOURCE ${MC_DIR}/launcher.js)
binary(SOURCE ${MC_DIR}/modules/xm_cli.js MODULE CLI)
binary(SOURCE ${MC_DIR}/modules/xm_console.js MODULE console)
binary(SOURCE ${MC_DIR}/modules/xm_debug.js MODULE debug)
binary(SOURCE ${MC_DIR}/modules/xm_env.js MODULE env)
binary(SOURCE ${MC_DIR}/modules/xm_files.js MODULE files)
binary(SOURCE ${MC_DIR}/modules/xm_socket.js MODULE socket)
binary(SOURCE ${MC_DIR}/modules/xm_stringview.js MODULE stringview)
binary(SOURCE ${MC_DIR}/modules/xm_system.js MODULE system)
binary(SOURCE ${MC_DIR}/modules/xm_timeinterval.js MODULE timeinterval)
binary(SOURCE ${MC_DIR}/modules/xm_timer.js MODULE timer)
binary(SOURCE ${MC_DIR}/modules/xm_watchdogtimer.js MODULE watchdogtimer)
binary(SOURCE ${MC_DIR}/modules/xm_wifi.js MODULE wifi)
binary(SOURCE ${MC_DIR}/tools/print_ski.js)
binary(SOURCE ${MC_DIR}/tools/xssign.js)

add_custom_target(
	host_fs
	COMMAND ${CMAKE_COMMAND} -E make_directory $ENV{HOME}/tmp/mc
	COMMAND ${CMAKE_COMMAND} -E copy_directory ${XS6}/sources/mc/data $ENV{HOME}/tmp/mc
	)

add_custom_command(
	OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/mc.xsa ${DEST_DIR}/mc.xs.c ${DEST_DIR}/mc.xs.h
	COMMAND ${XSL} -a mc -o ${CMAKE_CURRENT_BINARY_DIR} -b ${DEST_DIR} -r 97 ${MC_DEPS}
	COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_BINARY_DIR}/mc.xsa ${XS6_MODULES_DIR}/mc.xsa
	DEPENDS ${MC_DEPS}
	)
add_custom_target(mc.xsa DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/mc.xsa)
list(APPEND SOURCES ${DEST_DIR}/mc.xs.c ${DEST_DIR}/mc.xs.h)
